Allow support to pass function in the context
datavis-tech/json-templates pull request #33
Opened 2020-09-16 10:39 UTC by pranavwani

Description: Useful, for applying the function in the payload.

Usecase:
```
const parse = require("json-templates");
const faker = require("faker");

const context = {
   $name: faker.name.findName,
   $email: faker.internet.email
}

const content = `{
  "name": "{{$name}}"   
}`

const template = parse(content);

const payload = template({ ...context });
```

2020-09-16 15:02 UTC, curran commented
Interesting...

I'm curious, why not do it like this?

```js
const parse = require("json-templates");
const faker = require("faker");

const context = {
   $name: faker.name.findName(),  // <-------- This changed
   $email: faker.internet.email
}

const content = `{
  "name": "{{$name}}"   
}`

const template = parse(content);

const payload = template({ ...context });
```

2020-09-17 04:30 UTC, pranavwani commented
@curran for generating dynamic value needs to assign a prototype rather than calling a function because by calling a function it will initialize with the static value.

Requirement: Single variable call multiple times at runtime.

**Output:**
By assigning function call
```
{
  "name": "Eva Quigley"   
}
{
  "name": "Eva Quigley"   
}

```

2020-09-17 14:35 UTC, curran commented
Interesting...

I'm curious why not do this?

```js
setInterval(() => {
  const context = {
    $name: faker.name.findName(), // <-------- This changed
    $email: faker.internet.email,
  };

  const content = `{
    "name": "{{$name}}"   
  }`;

  const template = parse(content);

  const payload = template({ ...context });
  console.log(payload);
}, 2000);
```

2020-09-17 14:35 UTC, curran commented
I'm open to accept the PR, just want to understand the use case more deeply.

Please add a test case that covers this new feature. Thanks!

2020-09-18 17:27 UTC, pranavwani commented
@curran test case is added, two dependencies were added to full fill the use case.

2020-09-19 13:03 UTC, curran requested changes
I appreciate your work here, but I see several issues with this PR:

 * It changes existing dependency versions, which is not required.
 * It adds new dependencies that are not required.
 * The test is overly complex, no need to use the UID function itself.
 * There are incidental formatting changes.

What I'd like to see in a PR is a _very simple_ test that only serves the purpose of verifying the new code path. No need to introduce additional dependencies.

Please, it might be easiest to start a new PR that only includes the feature implementation and a single new test. No formatting changes, no dependency changes.

Thanks!

2020-09-19 13:03 UTC, curran commented on test.js
> +    it('should compute template with Function', function () {
This test is overly complex. The usage of uuid is not required. You can mock it out to return a fixed value.

The test should only test the feature, not additional things.

2020-09-24 03:41 UTC, pranavwani commented
@curran sorry for the delay. I'll close this PR because of the code format issues and create the new one by adding the test case without any dependencies.

2020-09-24 03:41 UTC, closed without merging

2020-09-24 03:42 UTC, pranavwani commented on package.json
> +    "rollup": "^0.65.2",
I think yarn auto-updates the libs.

2020-09-24 03:43 UTC, pranavwani commented on package.json
> +    "faker": "^5.1.0",
I'll remove them

2020-09-24 03:43 UTC, pranavwani commented on test.js
> +          defaultValue: 'bar',
:+1:

2020-09-24 03:46 UTC, pranavwani commented on test.js
> +      assert.deepEqual(template.parameters, [
Ya, I've used Prettier. But I'll remove it.

2020-09-24 03:46 UTC, pranavwani commented on test.js
> +    it('should compute template with Function', function () {
I'll keep it simple.

2020-09-24 14:52 UTC, curran commented
Perfect! Thank you 🙏