Added: default values can be evaluated
datavis-tech/json-templates pull request #41
Opened 2021-10-26 21:47 UTC by Bootta11

Now default value can be array, object or some other evaluated expression.

2021-12-10 11:37 UTC, Bootta11 commented
Any progress on this.

2021-12-10 12:46 UTC, curran requested changes
Thanks for this, but I'm not convinced that it is required.

I would consider an implementation based on using `eval` behind an opt-in feature flag.

Also, it should be relatively straightforward to do the evaluation in a secondary traversal of the output. Perhaps that could be added to the library as a separate function?

2021-12-10 12:46 UTC, curran commented on package.json
> +    "notevil": "^1.3.3",
I'd rather not introduce a new dependency, especially on a package that hasn't been updated in 2 years. https://www.npmjs.com/package/notevil

Is there any way this could be done without this dependency? Maybe we could just use `eval`, and put it behind an opt-in flag.

Another idea - could the evaluation possibly be done in a secondary step, based on traversing the output?

2021-12-17 11:35 UTC, Bootta11 commented
Sry for late reply.

I added parameter so eval is optional. Eval is not safe so purposely I used notevil lib.

2021-12-17 18:00 UTC, curran commented
Excellent! Thank you for this work.

I really do not want to add notevil as a dependency to this package.

I'm curious, why is this required? What do you need to do? Could the existing function value feature not accomplish the same thing?

https://github.com/datavis-tech/json-templates/blob/master/test.js#L310

2023-07-02 23:00 UTC, mytharcher commented
IMHO, we'd better not to add this feature. It will really make the logic more complicated. Whenever using `eval` or `RegExp` to do so is not a good solution, which comes with security risk and worse performance.

If just for the default value, a better workaround is to deal with the context scope data outside, but not in `json-templates`.

2023-07-04 13:34 UTC, curran commented
Closing as this is out of scope for the library

2023-07-04 13:34 UTC, closed without merging