Fix value inside string and date to ISO string
datavis-tech/json-templates pull request #48
Opened 2024-03-12 04:39 UTC by mytharcher

Values inside of a string should not be returned as only the value. Better to be replaced to `.toString()`ed string value and join the template.

Example:

```
parse('abc{{a}}def')({ a: 1 }) // should be 'abc1def' but 1 for now
```

Additionally, the default `toString()` on `Date` value produce a readable string, but hard to use. So when date variable inside a string, change it by `.toISOString()`.

2024-03-13 14:40 UTC, curran requested changes
This looks great!

You mentioned an example case in the PR:

```
parse('abc{{a}}def')({ a: 1 }) // should be 'abc1def' but 1 for now
```

Would you be willing to add that as a test case as well? It would be great to have that in the tests to make them more thorough. Thank you so much!

2024-04-22 07:08 UTC, mytharcher commented
Hi, @curran !

Hope you got a little time to have a check on the test case I have added.

Anything not OK please ping me.

2024-04-23 14:11 UTC, curran commented
Oh nice! Sorry I missed the commit, I didn't realize it was added.

2024-04-23 14:11 UTC, curran approved these changes
LGTM! Thank you for this.

2024-04-23 14:11 UTC, merged

2024-04-23 14:15 UTC, curran commented
Released in https://github.com/datavis-tech/json-templates/releases/tag/v5.1.0